openapi: 3.0.0
info:
  version: 1.0.0
  title: BoostTeams API docs
  description: BoostTeams의 API 문서입니다
  license:
    name: MIT
servers:
  - url: 'https://www.boostteams.kro.kr'
    description: BoostTeams Server
tags:
  - name: auth
    description: Join / Login / Logout
  - name: schedule
    description: Calendar Page
  - name: team
    description: Team Page
  - name: user
    description: User Manage
paths:
  /api/auth/login:
    post:
      summary: 로그인하기
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userEmail:
                  type: string
                userPassword:
                  type: string
              example:
                userEmail: test@test.com
                userPassword: 1qwrj1233ssd
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1api~1auth~1info/get/responses/200/content/application~1json/schema'
        '401':
          description: error
  /api/auth/github:
    get:
      summary: github
      tags:
        - auth
      responses:
        '200':
          description: 성공
        '404':
          description: error
  /api/auth/github/callback:
    get:
      summary: github/callback
      tags:
        - auth
      responses:
        '200':
          description: 성공
        '404':
          description: error
  /api/auth/signup:
    post:
      summary: 회원가입하기
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                userEmail:
                  type: string
                userPassword:
                  type: string
              example:
                userName: testName
                userEmail: test@test.com
                userPassword: 1qwrj1233ssd
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  signup:
                    type: boolean
                example:
                  signup: true
        '409':
          description: error
  /api/auth/info:
    get:
      summary: 유저 정보 가져오기
      tags:
        - auth
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
        '401':
          description: error
  /api/auth/signout:
    get:
      summary: 회원 탈퇴
      tags:
        - auth
      responses:
        '204':
          description: 성공
        '401':
          description: error
  /api/schedules:
    get:
      summary: 일정 가져오기
      tags:
        - schedule
      parameters:
        - name: team_id
          in: query
          required: true
          description: 대상 팀 id
          schema:
            type: integer
        - name: start_date
          in: query
          required: true
          description: 시작 날짜
          schema:
            type: string
        - name: end_date
          in: query
          required: true
          description: 끝 날짜
          schema:
            type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    team_id:
                      type: integer
                    start_date:
                      type: string
                    end_date:
                      type: string
                    content:
                      type: string
                    color:
                      type: integer
                    repeat_id:
                      type: string
                    repeat_option:
                      type: integer
                    schedule_id:
                      type: integer
                example:
                  - schedule_id: 135
                    team_id: 1
                    title: 회의 - 수정
                    start_date: 2021-11-09T05:00:00.000Z
                    end_date: 2021-11-09T06:00:00.000Z
                    repeat_id: 837148eb-b3b6-45a7-8f86-0517f10ffe10
                    repeat_option: 0
                    content: 화요일 회의 - 수정
                    color: 4
                  - schedule_id: 139
                    team_id: 1
                    title: hi
                    start_date: 2021-11-09T12:45:00.000Z
                    end_date: 2021-11-09T13:30:00.000Z
                    repeat_id: 288d71e8-06a1-46c9-93fe-0299b949dbc6
                    repeat_option: 0
                    content: 22
                    color: 0
                  - schedule_id: 146
                    team_id: 1
                    title: hihi
                    start_date: 2021-11-11T09:30:00.000Z
                    end_date: 2021-11-11T10:00:00.000Z
                    repeat_id: 2069433b-3a19-47a2-b2f0-62008729a925
                    repeat_option: 0
                    content: hihi
                    color: 3
        '404':
          description: error
    post:
      summary: 일정 추가하기
      tags:
        - schedule
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                team_id:
                  type: integer
                title:
                  type: string
                start_date:
                  type: string
                end_date:
                  type: string
                repeat_option:
                  type: integer
                repeat_count:
                  type: integer
                content:
                  type: string
                color:
                  type: integer
              example:
                team_id: 1
                title: 매일 5번 반복
                start_date: 2021-11-01T03:00:00.000Z
                end_date: 2021-11-01T04:00:00.000Z
                repeat_option: 1
                repeat_count: 5
                content: 매일 5번 반복
                color: 2
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    team_id:
                      type: integer
                    start_date:
                      type: string
                    end_date:
                      type: string
                    content:
                      type: string
                    color:
                      type: integer
                    repeat_id:
                      type: string
                    repeat_option:
                      type: integer
                    schedule_id:
                      type: integer
                example:
                  - title: 매일 5번 반복
                    team_id: 1
                    start_date: 'Mon Nov 01 2021 12:00:00 GMT+0900'
                    end_date: 'Mon Nov 01 2021 13:00:00 GMT+0900'
                    content: 매일 5번 반복
                    color: 2
                    repeat_id: d4a826b3-719d-4954-a250-e772821dc897
                    repeat_option: 1
                    schedule_id: 157
                  - title: 매일 5번 반복
                    team_id: 1
                    start_date: 'Tue Nov 02 2021 12:00:00 GMT+0900'
                    end_date: 'Tue Nov 02 2021 13:00:00 GMT+0900'
                    content: 매일 5번 반복
                    color: 2
                    repeat_id: d4a826b3-719d-4954-a250-e772821dc897
                    repeat_option: 1
                    schedule_id: 156
                  - title: 매일 5번 반복
                    team_id: 1
                    start_date: 'Wed Nov 03 2021 12:00:00 GMT+0900'
                    end_date: 'Wed Nov 03 2021 13:00:00 GMT+0900'
                    content: 매일 5번 반복
                    color: 2
                    repeat_id: d4a826b3-719d-4954-a250-e772821dc897
                    repeat_option: 1
                    schedule_id: 158
        '409':
          description: error
  '/api/schedules/{schedule_id}':
    delete:
      summary: 일정 삭제하기
      tags:
        - schedule
      parameters:
        $ref: '#/paths/~1api~1schedules~1%7Bschedule_id%7D/put/parameters'
      responses:
        '204':
          description: 성공
        '409':
          description: error
    put:
      summary: 일정 수정하기
      tags:
        - schedule
      parameters:
        - name: schedule_id
          in: path
          required: true
          description: shedule id
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                start_date:
                  type: string
                end_date:
                  type: string
                repeat_option:
                  type: integer
                repeat_count:
                  type: integer
                content:
                  type: string
                color:
                  type: integer
              example:
                title: 매일 5번 반복
                start_date: 2021-11-01T03:00:00.000Z
                end_date: 2021-11-01T04:00:00.000Z
                repeat_option: 1
                repeat_count: 5
                content: 매일 5번 반복
                color: 2
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  schedule_id:
                    type: integer
                  team_id:
                    type: integer
                  title:
                    type: string
                  start_date:
                    type: string
                  end_date:
                    type: string
                  repeat_id:
                    type: string
                  content:
                    type: string
                  color:
                    type: integer
                example:
                  schedule_id: 135
                  team_id: 1
                  title: 회의 - 수정
                  start_date: 2021-11-09T05:00:00.000Z
                  end_date: 2021-11-09T06:00:00.000Z
                  repeat_id: 837148eb-b3b6-45a7-8f86-0517f10ffe10
                  content: 화요일 회의 - 수정
                  color: 4
        '409':
          description: error
  /api/users:
    patch:
      summary: 유저 닉네임 변경하기
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                newName:
                  type: string
      responses:
        '204':
          description: 성공
        '401':
          description: 유저 정보 없음
        '409':
          description: 이미 존재하는 닉네임
  /api/teams:
    get:
      summary: '팀, 초대 목록 [team-user]'
      tags:
        - team
      responses:
        '201':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    team_user_id:
                      type: integer
                    state:
                      type: boolean
                    role:
                      type: integer
                    team:
                      type: object
                      properties:
                        team_id:
                          type: integer
                        team_name:
                          type: string
                        team_desc:
                          type: string
        '409':
          description: error
    post:
      summary: '팀 생성, [team, team-user]'
      tags:
        - team
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                team_name:
                  type: string
                team_desc:
                  type: string
      responses:
        '201':
          description: 성공
        '409':
          description: error
  '/api/teams/{teamId}':
    get:
      summary: 팀 정보 가져오기
      tags:
        - team
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/paths/~1api~1teams~1%7BteamId%7D/put/requestBody/content/application~1json/schema'
        '404':
          description: error
    put:
      summary: '팀 수정 [team]'
      tags:
        - team
      parameters:
        $ref: '#/paths/~1api~1teams~1%7BteamId%7D/get/parameters'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                team_id:
                  type: integer
                team_name:
                  type: string
                team_desc:
                  type: string
      responses:
        '200':
          description: 성공
        '409':
          description: error
    delete:
      summary: '팀 삭제, [team]'
      tags:
        - team
      parameters:
        $ref: '#/paths/~1api~1teams~1%7BteamId%7D/get/parameters'
      responses:
        '204':
          description: 성공
        '409':
          description: error
  '/api/teams/{teamId}/users':
    get:
      summary: 팀의 모든 유저 리스트 가져오기
      tags:
        - team
      parameters:
        $ref: '#/paths/~1api~1teams~1%7BteamId%7D/get/parameters'
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    team_user_id:
                      type: integer
                    state:
                      type: boolean
                    role:
                      type: integer
                    user:
                      type: object
                      properties:
                        user_id:
                          type: integer
                        user_name:
                          type: string
                        user_color:
                          type: integer
        '404':
          description: error
  '/api/teams/{teamId}/invitations':
    post:
      summary: '초대 전송 [team-user]'
      tags:
        - team
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_email:
                  type: string
                team_id:
                  type: integer
      responses:
        '201':
          description: 성공
        '404':
          description: error
    patch:
      summary: '초대 수락 [team-user]'
      tags:
        - team
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                team_id:
                  type: integer
      responses:
        '204':
          description: 성공
        '409':
          description: error
    delete:
      summary: '초대 거절 [team-user]'
      tags:
        - team
      responses:
        '204':
          description: 성공
        '409':
          description: error
  '/api/teams/{teamId}/users/{userId}':
    patch:
      summary: '권한 변경 [team-user]'
      tags:
        - team
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/paths/~1api~1teams~1%7BteamId%7D~1invitations/patch/requestBody/content/application~1json/schema'
      responses:
        '204':
          description: 성공
        '409':
          description: error
    delete:
      summary: '팀원 강퇴 [team-user]'
      tags:
        - team
      responses:
        '204':
          description: 성공
        '409':
          description: error
